services:
  db:
    image: postgres:latest
    container_name: postgres_container_books
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root123"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
