services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root123"
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
